[tools]
rojo = { source = "rojo-rbx/rojo", version = "=7.2.1"}
selene = {source = "Kampfkarren/selene", version = "=0.16.0"}
remodel = {source = "rojo-rbx/remodel", version = "=0.7.1"}
wally = {source = "upliftgames/wally", version = "=0.3.1"}