[package]
name = "nobledraconian/dragon-engine"
description = "Microservice-based framework for Roblox experiences"
version = "0.1.0-rc.8"
authors = ["Noble_Draconian"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"

[dependencies]
Roblox-LibModules = "nobledraconian/roblox-libmodules@3.0.0"
Cmdr = "evaera/cmdr@1.9.0"