name: Lua linting
on:
  push:
    branches:
    - master
    paths:
      - 'src/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
jobs:
  selene-lint:
    name: Lint src/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      
      - name: Setup foreman
        uses: rojo-rbx/setup-foreman@6d3c8043db88319f8482262680b37f73595a8686
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name : Run selene
        run: |
          selene src/