on:
  release:
    types: [published]

jobs:
  package-publish:
    name: Publish package to wally registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup aftman
        uses: ok-nick/setup-aftman@c52e3c91524316f8ca696574d576ea21b7518ec8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish wally package
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
        run: |
          mkdir -p ~/.wally
          echo "$WALLY_AUTH" > ~/.wally/auth.toml
          wally publish